### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by BhavinBhadani** [strekfus/FloatRatingView#11]
I just got this error whenever i am enter in storyboard...after some time it disappears...but  it gives slow performance error...how  to get rid of this  

        error: IB Designables: Failed to render instance of FloatRatingView: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.

**Comment by strekfus** [comment]
Sorry for the late reply! I never see this error. What version of Xcode are you using?

**Comment by BhavinBhadani** [comment]
xcode 6.3.1
